// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAio2I2K-Nj0zTE9AH2TKULssoU-q21iao',
    appId: '1:381376292200:web:c1402b62c54a35d338e2dd',
    messagingSenderId: '381376292200',
    projectId: 'quest-guide-for-tourists',
    authDomain: 'quest-guide-for-tourists.firebaseapp.com',
    storageBucket: 'quest-guide-for-tourists.firebasestorage.app',
    measurementId: 'G-79KRE3GK8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0zckVH-kCbXEtNXvYw99kvtYpzg1BKj0',
    appId: '1:381376292200:android:87956a6645afcbef38e2dd',
    messagingSenderId: '381376292200',
    projectId: 'quest-guide-for-tourists',
    storageBucket: 'quest-guide-for-tourists.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJplGyrHuTmTkOBSNm6N-VBDq9hn_NAY',
    appId: '1:381376292200:ios:d0d463c632740faf38e2dd',
    messagingSenderId: '381376292200',
    projectId: 'quest-guide-for-tourists',
    storageBucket: 'quest-guide-for-tourists.firebasestorage.app',
    iosBundleId: 'com.example.questGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQJplGyrHuTmTkOBSNm6N-VBDq9hn_NAY',
    appId: '1:381376292200:ios:d0d463c632740faf38e2dd',
    messagingSenderId: '381376292200',
    projectId: 'quest-guide-for-tourists',
    storageBucket: 'quest-guide-for-tourists.firebasestorage.app',
    iosBundleId: 'com.example.questGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAio2I2K-Nj0zTE9AH2TKULssoU-q21iao',
    appId: '1:381376292200:web:83aa6869f4e10ae538e2dd',
    messagingSenderId: '381376292200',
    projectId: 'quest-guide-for-tourists',
    authDomain: 'quest-guide-for-tourists.firebaseapp.com',
    storageBucket: 'quest-guide-for-tourists.firebasestorage.app',
    measurementId: 'G-6HF0VW4WS8',
  );
}
